('','Electrician'),
('','Plumber'),
('','Carpenter'),
('','Painter'),
('','Mason'),
('','Aluminium door worker'),
('','Welder & fabricator')
('','Distilled water supply'),
('','Security Guard'),
('','Tailor Service'),
('','Packer & Movers'),
('','Gardener'),
('','House keeping'), 
('','Medicine delivery'),
('','A.C. repair'),
('','Washing machine'),
('','TV'),
('','Gyser'), 
('','Refrigerator'),
('','Inverter'),
('','Microwave'),
('','Water purifier'),
('','Borewell water pump'),
('','DTH'),
('','Solar heater'),
('','Computer/Laptop'),
('','Mobile'),
('','Printer'),
('','CCTV'),
('','Xerox'),
('','Water cooler'),
('','Civil engineer'),
('','Architect'),
('','Contractor'),
('','Interior designer'),
('','False ceiling'),
('','Water purifier'),
('','PVC'),
('','POP'),
('','Vehicle'),
('','Car repair'),
('','Bike repair'),
('','Breakdown Service'),
('','Car wash'),
('','Car renting'),
('','C.A. (business)'),
('','C.A. (I.T. Filling)'),
('','Visa service'),
('','GST'),
('','Lawyer'),
('','Pan card service'),
('','Notary'),
('','Passport'),
('','Home cleaning'),
('','Bathroom cleaning'),
('','Kitchen cleaning'),
('','Sofa cleaning'),
('','Carpet cleaning'),
('','Window/glass cleaning'),
('','Office cleaning'),
('','Pest control'),
('','Sewage cleaning'),
('','Water tank cleaning'),
('','Laundry service'),
('','Health & Fitness'),
('','Dietician'),
('','Nutritionist'),
('','Yoga trainer'),
('','Nurse'),
('','Beauty & salon'),
('','Bridal make-up'),
('','Facial'),
('','Threading'),
('','Pedicure/manicure'),
('','Mehendi artists'),
('','Occasion & event service'),
('','Wedding photography'),
('','Pre-wedding photography'),
('','Events photography'),
('','Baby photography'),
('','Maternity photography'),
('','Product shoot'),
('','DJ/music party shoot'),
('','Birthday event'),
('','Wedding event'),
('','Engagement event'),
('','Reception event'),
('','Baby shower event')